### ISSUE TITLE
User defined AIF - doing it wrong?

### ISSUE THREAD

**Issue by elijahrockers** [bjw34032/dcemriS4#2]
I am attempting to use individual user-defined AIFs for each subject, as opposed to the cohort fitted AIFs supplied. Here is the function call:

    fit <- dcemri.lm(con, x, mat, model="extended", aif="empirical", user=AIF, verbose=TRUE)

Where the 'AIF' object is a vector of 180 concentration values corresponding to the arterial input function.

When I use `aif=fritz.hansen` the total processing takes only 30 mins to an hour or so. With this user defined AIF, the processing has been running for 8 hours, so I think something is not quite right.

What is the correct way to incorporate user-defined AIFs into the analysis?

**Comment by elijahrockers** [comment]
OK it looks like it was just taking a much longer time than I anticipated. It finished over the weekend.

**Comment by bjw34032** [comment]
Dear Elijah,

Hi, sorry for the delayed response.  Yes, using a user-defined AIF carries
with it a substantial advantage as you discovered... the convolution
operation in the compartmental model is performed numerically instead of
analytically when using a parametric model for the AIF.  One idea would be
to fit a parametric AIF to your empirical data in order to take advantage
of the computational inefficiencies.   I'm glad it worked in the end.


Cheers, Brandon
